### ISSUE TITLE
Error when dropping peaks in chrY

### ISSUE THREAD

**Issue by nbpeterson3** [stjude-biohackathon/ECLIPSE#11]
When calling `run_rose`, error occurs because `seqnames` returns an `Rle` object and the comparison does not return a logical for `which`.

> enhancers <- run_rose(treatment = sample.bam, peaks = peaks)
Sample BAM file: ENCFF640GBC.bam
Reading peaks
Stitching peaks with stitch distance of 12500
Error in which(seqnames(peaks_stitched) == "chrY") : 
  argument to 'which' is not logical

**Comment by j-andrews7** [comment]
Your solution was more elegant than mine and didn't require more dependencies, so went with it.
