### ISSUE TITLE
Add enhancer annotation parameters.

### ISSUE THREAD

**Issue by j-andrews7** [stjude-biohackathon/ECLIPSE#5]
I think this should be simple with `detailRanges` from [csaw](https://bioconductor.org/books/release/csawBook/annotation-and-visualization.html). This will be added to `run_rose` function.

**Comment by nbpeterson3** [comment]
`detailRanges` has a few immediately relevant parameters: 

- `dist` which specifies a flanking distance to annotate (default = `5000`)
- `promoter` which defines distances upstream / downstream of the TSS in the `TxDb` object (default = `c(3000, 1000)`)
- `ignore.strand` indicates whether strandedness in the provided `GRanges` object should be ignored (default = `TRUE`)
- `name.field` indicates which column from `orgdb` to use as a gene name (default is gene symbol)

I'm thinking about including these parameters in `run_rose` for the user to define if they wish, but wasn't going to change the default values.  

When provided a `GRanges` object, the output of `detailRanges` is a list of character vectors, shown here as a data frame. I was just going to add this to the `GRanges` object (that `run_rose` returns) as meta data.

This all sound ok?

![Screenshot 2024-10-22 at 1 57 03 PM](https://github.com/user-attachments/assets/d4691056-9735-43e6-9a97-a6c535051ee9)

**Comment by j-andrews7** [comment]
Yup, that sounds good! Just a few things. By default, we can try to match the ROSE parameters for distance to annotate and all. By default, it goes out to 100kb for its "distal" genes.

It _would_ be nice to add an additional parameter or two to filter for "active" genes. This could be done a few ways. The most simple is to just accept a list of gene identifiers that the user can provide (e.g. from RNA-seq or such). Another approach would be to limit to transcripts with a peak overlapping their promoter, indicating that it's expressed. 

Call it `active.genes` for the first parameter, and maybe `identify.active.genes` as a logical for the second approach. If `active.genes` is provided, `identify.active.genes` would be ignored. These would be `NULL` and `FALSE` respectively by default.

**Comment by j-andrews7** [comment]
Fixed by #12.
